[package]
name = "passkey_verification_test"
version = "0.1.0"
edition = "2021"

[dependencies]
p256 = "0.13.2"
sha2 = "0.10.8"
rand = "0.8.5"
num-bigint = "0.4.4"
num-traits = "0.2.17"
hex = "0.4.3"

[[bin]]
name = "generate_test_data"
path = "src/generate_test_data.rs"
